### ISSUE TITLE
使用微星B460M迫击炮 WiFi版的主板，WiFi可以使用，蓝牙无法使用问题

### ISSUE THREAD

**Issue by QQ3233** [myqqiu/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630#42]
使用微星B460M迫击炮 WiFi版的主板，网卡是inel ax200（0x8086,0x2723,0x8086,0x0084），使用AirportItlwm_v1.2.0_stable_BigSur.kext.zip+IntelBluetoothFirmware+IntelBluetoothInjector驱动，WiFi可以使用，蓝牙无法使用问题（设置面板和网络李里面都没有蓝牙选项，菜单栏有蓝牙图标但图标上有斜杠）
![图片](https://user-images.githubusercontent.com/74389062/105431589-da278080-5c90-11eb-980c-8e1c5206f92f.png)
![图片](https://user-images.githubusercontent.com/74389062/105431641-f75c4f00-5c90-11eb-864b-dad0bc77ba94.png)
![图片](https://user-images.githubusercontent.com/74389062/105431937-96814680-5c91-11eb-9174-621e52acf46d.png)
![图片](https://user-images.githubusercontent.com/74389062/105432042-c7fa1200-5c91-11eb-85f2-a1a2abde9c45.png)
![图片](https://user-images.githubusercontent.com/74389062/105432684-09d78800-5c93-11eb-9b93-0866de5128af.png)

**Comment by Turhapuro** [comment]
Did you check if intel Bluetooth appear to HS08 port? USB HS08 port need to be internal type to be recognized. (Recently I changed AX200 to Broadcom card. That's why in picture it is BRCM20702 hub. For intel it should be seen as IOUSBHostDevice.)
I made custom USBPorts.kext to get it work right and needed keep XHCI-unsupported.kext so intel BT is recognized correctly.

Here is link to make your own USB poet mapping
https://dortania.github.io/OpenCore-Post-Install/usb/#macos-and-the-15-port-limit

![Screen Shot 2021-01-25 at 11 06 10](https://user-images.githubusercontent.com/68905448/105652823-971e1500-5efd-11eb-811d-1fe4341f1b91.png)

**Comment by QQ3233** [comment]
@Turhapuro when i do a usb mapping,no HS07 and HS08 show in list.
![图片](https://user-images.githubusercontent.com/74389062/105657278-fb8da400-5efe-11eb-9d6e-09f46b691257.png)

**Comment by Turhapuro** [comment]
Which ACPI files you use? You should remove SSDT-UIAC.aml from your OC. 
SSDT-UIAC.aml you use, have USB ports already mapped as I see from your picture above and that doesnt work B460M Wifi motherboard. Try do again USB port mapping after removing SSDT-UIAC.aml from your OC and rebooting.

Make sure that setting your config.plist have: config.plist -> Kernel -> Quirks -> XhciPortLimit -> True 
Then you should see all USB ports you have in your motherboard using USB port mapping.

You can change USB port type using command T:9:255  , where 9 is post and 255 = USB port type internal

**Comment by QQ3233** [comment]
@Turhapuro It works! Thanks a lot

**Comment by Turhapuro** [comment]
Glad to hear that :)
